# Configure main menu and social menu
#[[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "Steam"
name = "Steam"
url = "https://steamcommunity.com/profiles/76561199051896101/"

[social.params]
icon = "steam"

[[social]]
identifier = "Mastodon"
name = "Mastodon"
url = "https://alive.bar/@elysium"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "Discord"
name = "Discord"
url = "https://discordapp.com/users/920200091367792691"

[social.params]
icon = "brand-discord"
